---
title: "Comparison to other methods"
---

```{r, include = FALSE}
set.seed(4357)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this article we compare our package against the results from:

+ The [NobBS](https://github.com/sarahhbellum/NobBS) package.
+ The [nowcaster](https://covid19br.github.io/nowcaster/index.html) package.
+ The [nowcasting](https://github.com/nmecsys/nowcasting) package.
+ The [epinowcast](https://package.epinowcast.org/articles/model.html) package.

## NobBS

Here we reproduce the example from the `README.md` file:

```{r}
library(NobBS)
data("denguedat")
now <- as.Date("1990-10-01")

test_nowcast <- NobBS(data = denguedat, units = "1 week", now = now,
                      onset_date = "onset_week", report_date = "report_week")
```

and compare against the `diseasenowcasting` package:

```{r}
library(diseasenowcasting)
library(posterior)
library(tidyverse)

predictions <- nowcast(denguedat, "onset_week", "report_week",
                       now = now, method = "variational",
                       priors = set_priors(nu_is_constant = F))
```

which, after formating, 

```{r}
#Get the predicted values in a nice format
predicted_values <- predictions$generated_quantities |>
  posterior::as_draws() |>
  posterior::subset_draws("N_predict") |>
  posterior::summarise_draws() |>
  dplyr::mutate(.strata = as.numeric(stringr::str_remove_all(variable,".*\\[.*,|\\]"))) |>
  dplyr::mutate(.tval = as.numeric(stringr::str_remove_all(variable,".*\\[|,.*\\]"))) |>
  dplyr::left_join(
    predictions$data$preprocessed_data |>
      dplyr::distinct(.tval, onset_week)
  )

obs <- predictions$data$preprocessed_data |>
  dplyr::group_by(onset_week) |>
  dplyr::summarise(n = sum(n))
```

Result in a better prediction than the `NobBS` default one:

```{r, warning=FALSE}
# Create plot
ggplot() +
  geom_ribbon(aes(x = onset_week, ymin = q5, ymax = q95, fill = "diseasenowcasting"),
              data = predicted_values, alpha = 0.25) +
  geom_ribbon(aes(x = onset_date, ymin = lower, ymax = upper, fill = "NobBS"),
              data = test_nowcast$estimates, alpha = 0.25) +
  geom_line(aes(x = onset_week, y = n, color = "Train data", fill = "Train data"), data = obs) +
  geom_line(aes(x = onset_week, y = mean, color = "diseasenowcasting"),
            data = predicted_values, linetype = "dotted") +
  geom_line(aes(x = onset_date, y = estimate, color = "NobBS"), data = test_nowcast$estimates) +
  geom_point(aes(x = onset_week, y = n, color = "All data", fill = "All data"), data =
              denguedat |>
               dplyr::group_by(onset_week) |>
               dplyr::count() |>
               dplyr::filter(onset_week <= !!now)) +
  theme_bw() +
  scale_color_manual("Package",
        values = c("NobBS" = "#3B9AB2", "diseasenowcasting" = "#E1AF00",
                   "All data" = "#F21A00",
                   "Train data" = "black")) +
  scale_fill_manual("Package",
        values = c("NobBS" = "#3B9AB2", "diseasenowcasting" = "#E1AF00",
                   "All data" = "#F21A00",
                   "Train data" = "black"))
```


