# =============================================================================
# Process roles for covariates
# =============================================================================

#' Tag covariates for a nowcasting process
#'
#' These helpers attach a lightweight S3 class to a covariate without changing
#' its values or removing any of its existing classes. `diseasenowcasting`
#' reads the tags when it prepares a `tbl_now` object:
#'
#' - event covariates affect the latent event/incidence process;
#' - delay covariates affect event-to-report timing;
#' - revision covariates affect report-to-revision timing.
#'
#' Untagged columns registered by `tbl.now::get_covariates()` remain event
#' covariates for backward compatibility. A vector may carry more than one tag.
#'
#' The helpers can be used on a vector, typically inside `dplyr::mutate()`, or
#' on a data frame / `tbl_now` with tidy-select expressions in `...`. When a
#' `tbl_now` is supplied without selections, all columns registered as
#' covariates are tagged.
#'
#' @param x A vector to tag, or a data frame / `tbl_now` containing covariates.
#' @param ... For data-frame inputs, tidy-select expressions identifying the
#'   columns to tag.
#'
#' @return `x`, with the requested process-role S3 class added.
#' @examples
#' x <- data.frame(day = 1:3, capacity = c(10, 12, 11))
#' x$capacity <- as_delay_covariates(x$capacity)
#' inherits(x$capacity, "delay_covariates")
#'
#' x <- as_revision_covariates(x, capacity)
#' inherits(x$capacity, "revision_covariates")
#' @name covariate_roles
NULL

.tag_covariate_role <- function(x, role) {
  marker <- paste0(role, "_covariates")
  old_class <- class(x)
  if (!marker %in% old_class) class(x) <- c(marker, old_class)
  x
}

.as_process_covariates <- function(x, ..., role) {
  dots <- rlang::enquos(...)
  if (!is.data.frame(x)) {
    if (length(dots)) {
      cli::cli_abort("Tidy-select expressions in `...` are only supported when `x` is a data frame.")
    }
    return(.tag_covariate_role(x, role))
  }

  columns <- if (length(dots)) {
    names(dplyr::select(as.data.frame(x), !!!dots))
  } else if (tbl.now::is_tbl_now(x)) {
    tbl.now::get_covariates(x) %||% character(0)
  } else {
    names(x)
  }
  if (!length(columns)) {
    cli::cli_abort("No covariate columns were selected to tag.")
  }
  for (column in columns) x[[column]] <- .tag_covariate_role(x[[column]], role)
  x
}

#' @rdname covariate_roles
#' @export
as_event_covariates <- function(x, ...) {
  .as_process_covariates(x, ..., role = "event")
}

#' @rdname covariate_roles
#' @export
as_delay_covariates <- function(x, ...) {
  .as_process_covariates(x, ..., role = "delay")
}

#' @rdname covariate_roles
#' @export
as_revision_covariates <- function(x, ...) {
  .as_process_covariates(x, ..., role = "revision")
}

#' Resolve the process role of every ordinary covariate column
#' @keywords internal
#' @noRd
.covariate_roles <- function(data) {
  frame <- as.data.frame(data)
  registered <- tryCatch(tbl.now::get_covariates(data), error = function(e) character(0))
  registered <- intersect(registered %||% character(0), names(frame))
  tagged <- lapply(c("event", "delay", "revision"), function(role) {
    marker <- paste0(role, "_covariates")
    names(frame)[vapply(frame, inherits, logical(1), what = marker)]
  })
  names(tagged) <- c("event", "delay", "revision")

  explicitly_tagged <- unique(unlist(tagged, use.names = FALSE))
  tagged$event <- unique(c(tagged$event, setdiff(registered, explicitly_tagged)))
  tagged
}

.restore_covariate_role_classes <- function(value, source) {
  markers <- intersect(
    class(source),
    c("event_covariates", "delay_covariates", "revision_covariates")
  )
  class(value) <- unique(c(markers, class(value)))
  value
}

.strip_covariate_role_classes <- function(value) {
  class(value) <- setdiff(
    class(value),
    c("event_covariates", "delay_covariates", "revision_covariates")
  )
  value
}

# vctrs uses double dispatch for join keys. A tagged stratum can therefore meet
# the corresponding untagged factor/character generated by tbl.now while it
# completes an observation grid. Preserve the role on the common type without
# changing the underlying factor levels or character values.
.covariate_role_ptype2_left <- function(x, y, ...) {
  .restore_covariate_role_classes(
    vctrs::vec_ptype2(.strip_covariate_role_classes(x), y, ...), x
  )
}
.covariate_role_ptype2_right <- function(x, y, ...) {
  .restore_covariate_role_classes(
    vctrs::vec_ptype2(x, .strip_covariate_role_classes(y), ...), y
  )
}
.covariate_role_cast_left <- function(x, to, ...) {
  .restore_covariate_role_classes(
    vctrs::vec_cast(
      .strip_covariate_role_classes(x),
      .strip_covariate_role_classes(to), ...
    ), to
  )
}
.covariate_role_cast_right <- function(x, to, ...) {
  vctrs::vec_cast(.strip_covariate_role_classes(x), to, ...)
}
.covariate_role_ptype2_both <- function(x, y, ...) {
  value <- vctrs::vec_ptype2(
    .strip_covariate_role_classes(x),
    .strip_covariate_role_classes(y), ...
  )
  .restore_covariate_role_classes(
    .restore_covariate_role_classes(value, x), y
  )
}
.covariate_role_cast_both <- function(x, to, ...) {
  .restore_covariate_role_classes(
    vctrs::vec_cast(
      .strip_covariate_role_classes(x),
      .strip_covariate_role_classes(to), ...
    ), to
  )
}

#' @export
vec_ptype2.event_covariates.event_covariates <- .covariate_role_ptype2_both
#' @export
vec_cast.event_covariates.event_covariates <- .covariate_role_cast_both
#' @export
vec_ptype2.delay_covariates.delay_covariates <- .covariate_role_ptype2_both
#' @export
vec_cast.delay_covariates.delay_covariates <- .covariate_role_cast_both
#' @export
vec_ptype2.revision_covariates.revision_covariates <- .covariate_role_ptype2_both
#' @export
vec_cast.revision_covariates.revision_covariates <- .covariate_role_cast_both

#' @export
vec_ptype2.event_covariates.factor <- .covariate_role_ptype2_left
#' @export
vec_ptype2.factor.event_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.event_covariates.factor <- .covariate_role_cast_left
#' @export
vec_cast.factor.event_covariates <- .covariate_role_cast_right
#' @export
vec_ptype2.delay_covariates.factor <- .covariate_role_ptype2_left
#' @export
vec_ptype2.factor.delay_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.delay_covariates.factor <- .covariate_role_cast_left
#' @export
vec_cast.factor.delay_covariates <- .covariate_role_cast_right
#' @export
vec_ptype2.revision_covariates.factor <- .covariate_role_ptype2_left
#' @export
vec_ptype2.factor.revision_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.revision_covariates.factor <- .covariate_role_cast_left
#' @export
vec_cast.factor.revision_covariates <- .covariate_role_cast_right

#' @export
vec_ptype2.event_covariates.character <- .covariate_role_ptype2_left
#' @export
vec_ptype2.character.event_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.event_covariates.character <- .covariate_role_cast_left
#' @export
vec_cast.character.event_covariates <- .covariate_role_cast_right
#' @export
vec_ptype2.delay_covariates.character <- .covariate_role_ptype2_left
#' @export
vec_ptype2.character.delay_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.delay_covariates.character <- .covariate_role_cast_left
#' @export
vec_cast.character.delay_covariates <- .covariate_role_cast_right
#' @export
vec_ptype2.revision_covariates.character <- .covariate_role_ptype2_left
#' @export
vec_ptype2.character.revision_covariates <- .covariate_role_ptype2_right
#' @export
vec_cast.revision_covariates.character <- .covariate_role_cast_left
#' @export
vec_cast.character.revision_covariates <- .covariate_role_cast_right

# Keep the lightweight role class through base vector operations. Existing
# classes (Date, factor, ordered, and so on) still receive their own methods via
# NextMethod().
#' @export
`[.event_covariates` <- function(x, ...) {
  .restore_covariate_role_classes(NextMethod(), x)
}
#' @export
`[.delay_covariates` <- function(x, ...) {
  .restore_covariate_role_classes(NextMethod(), x)
}
#' @export
`[.revision_covariates` <- function(x, ...) {
  .restore_covariate_role_classes(NextMethod(), x)
}
