# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_block_diagonal <- function(A, B, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_block_diagonal`, A, B, pstream__)
}

rep_diagonal_mat <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_diagonal_mat`, A, k, pstream__)
}

rep_vec <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_vec`, A, k, pstream__)
}

rep_vec_piecewise <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_vec_piecewise`, A, k, pstream__)
}

create_trend_matrix_block_A <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_matrix_block_A`, degree, pstream__)
}

create_trend_vector_block_L <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_vector_block_L`, degree, pstream__)
}

create_trend_matrix_block_R <- function(degree, is_constant, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_matrix_block_R`, degree, is_constant, pstream__)
}

get_num_elements_alpha_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_elements_alpha_trend`, degree, pstream__)
}

get_num_cols_A_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_cols_A_trend`, degree, pstream__)
}

get_num_rows_A_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_rows_A_trend`, degree, pstream__)
}

get_num_elements_L_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_elements_L_trend`, degree, pstream__)
}

get_num_cols_R_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_cols_R_trend`, degree, pstream__)
}

get_num_rows_R_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_rows_R_trend`, degree, pstream__)
}

create_seasonal_discrete_matrix_block_A <- function(num_seasons, season_duration, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_matrix_block_A`, num_seasons, season_duration, pstream__)
}

create_seasonal_discrete_vector_block_L <- function(num_seasons, season_duration, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_vector_block_L`, num_seasons, season_duration, pstream__)
}

create_seasonal_discrete_matrix_block_R <- function(num_seasons, season_duration, time, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_matrix_block_R`, num_seasons, season_duration, time, pstream__)
}

create_initial_seasonal_discrete_vector_block_alpha <- function(season_params, season_duration, error_term, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_initial_seasonal_discrete_vector_block_alpha`, season_params, season_duration, error_term, pstream__)
}

state_space_process_v3 <- function(num_steps, num_delays, num_strata, A_mu, A_nu, R_mu, R_nu, L_mu, L_nu, mu_0, xi_mu, nu_0, xi_nu, B_cnt, X_cnt, pstream__ = 0L) {
    .Call(`_diseasenowcasting_state_space_process_v3`, num_steps, num_delays, num_strata, A_mu, A_nu, R_mu, R_nu, L_mu, L_nu, mu_0, xi_mu, nu_0, xi_nu, B_cnt, X_cnt, pstream__)
}

dist_lpdf <- function(x, param_1, param_2, prior_spec, pstream__ = 0L) {
    .Call(`_diseasenowcasting_dist_lpdf`, x, param_1, param_2, prior_spec, pstream__)
}

