# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_block_diagonal <- function(A, B, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_block_diagonal`, A, B, pstream__)
}

rep_diagonal_mat <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_diagonal_mat`, A, k, pstream__)
}

rep_vec <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_vec`, A, k, pstream__)
}

rep_vec_piecewise <- function(A, k, pstream__ = 0L) {
    .Call(`_diseasenowcasting_rep_vec_piecewise`, A, k, pstream__)
}

append_val_2_vec <- function(A, val, pstream__ = 0L) {
    .Call(`_diseasenowcasting_append_val_2_vec`, A, val, pstream__)
}

append_vec_2_val <- function(val, A, pstream__ = 0L) {
    .Call(`_diseasenowcasting_append_vec_2_val`, val, A, pstream__)
}

create_trend_matrix_block_A <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_matrix_block_A`, degree, pstream__)
}

create_trend_vector_block_L <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_vector_block_L`, degree, pstream__)
}

create_trend_matrix_block_R <- function(degree, is_constant, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_trend_matrix_block_R`, degree, is_constant, pstream__)
}

get_num_elements_alpha_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_elements_alpha_trend`, degree, pstream__)
}

get_num_cols_A_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_cols_A_trend`, degree, pstream__)
}

get_num_rows_A_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_rows_A_trend`, degree, pstream__)
}

get_num_elements_L_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_elements_L_trend`, degree, pstream__)
}

get_num_cols_R_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_cols_R_trend`, degree, pstream__)
}

get_num_rows_R_trend <- function(degree, pstream__ = 0L) {
    .Call(`_diseasenowcasting_get_num_rows_R_trend`, degree, pstream__)
}

create_seasonal_discrete_matrix_block_A <- function(num_seasons, season_duration, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_matrix_block_A`, num_seasons, season_duration, pstream__)
}

create_seasonal_discrete_vector_block_L <- function(num_seasons, season_duration, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_vector_block_L`, num_seasons, season_duration, pstream__)
}

create_seasonal_discrete_matrix_block_R <- function(num_seasons, season_duration, time, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_seasonal_discrete_matrix_block_R`, num_seasons, season_duration, time, pstream__)
}

create_initial_seasonal_discrete_vector_block_alpha <- function(season_params, season_duration, error_term, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_initial_seasonal_discrete_vector_block_alpha`, season_params, season_duration, error_term, pstream__)
}

max_int <- function(a, b, pstream__ = 0L) {
    .Call(`_diseasenowcasting_max_int`, a, b, pstream__)
}

min_int <- function(a, b, pstream__ = 0L) {
    .Call(`_diseasenowcasting_min_int`, a, b, pstream__)
}

AR <- function(y, phi, t, pstream__ = 0L) {
    .Call(`_diseasenowcasting_AR`, y, phi, t, pstream__)
}

MA <- function(xi, theta, t, pstream__ = 0L) {
    .Call(`_diseasenowcasting_MA`, xi, theta, t, pstream__)
}

create_phi_AR <- function(phi, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_phi_AR`, phi, pstream__)
}

create_theta_MA <- function(theta, pstream__ = 0L) {
    .Call(`_diseasenowcasting_create_theta_MA`, theta, pstream__)
}

state_space_process <- function(num_steps, num_delays, num_strata, A_mu, A_nu, R_mu, R_nu, L_mu, L_nu, xi_mu_centered, xi_nu_centered, xi_mu_sd, xi_nu_sd, mu_0_centered, nu_0_centered, mu_0_sd, nu_0_sd, mu_0_mean, nu_0_mean, B_cnt, X_cnt, phi_AR, theta_MA, xi, pstream__ = 0L) {
    .Call(`_diseasenowcasting_state_space_process`, num_steps, num_delays, num_strata, A_mu, A_nu, R_mu, R_nu, L_mu, L_nu, xi_mu_centered, xi_nu_centered, xi_mu_sd, xi_nu_sd, mu_0_centered, nu_0_centered, mu_0_sd, nu_0_sd, mu_0_mean, nu_0_mean, B_cnt, X_cnt, phi_AR, theta_MA, xi, pstream__)
}

